version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: watersuply
      POSTGRES_PASSWORD: suplywater
      POSTGRES_DB: mywater
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: